export const EVENTS = {
    TOTEM: {
        SELECT_AREA: "SELECT_AREA",
        TURN_GENERATED: "TURN_GENERATED",
        TICKET_GENERATED: "TICKET_GENERATED",
    },
    MONITOR: {
        TICKET_GENERATED: "TICKET_GENERATED",
    },
    BACKOFFICE: {
        CALL_TICKET: "CALL_TICKET",
        CONNECTED_BOX: "CONNECTED_BOX",
        TICKET_GENERATED: "TICKET_GENERATED",
    },
}