export const EVENTS = {
    GENERAL: {
        CONNECTION: "connection",
        DISCONNECT: "disconnect",
        FINISH_TICKET: "FINISH_TICKET",
    },
    TOTEM: {
        SELECT_AREA: "SELECT_AREA",
        TURN_GENERATED: "TURN_GENERATED",
        TICKET_GENERATED: "TOTEM_TICKET_GENERATED",
    },
    MONITOR: {
        TICKET_GENERATED: "MONITOR_TICKET_GENERATED",
        FINISH_TICKET: "MONITOR_FINISH_TICKET",
        TICKET_CALLED: "TICKET_CALLED",
        RECALLING_TICKET_ALARM: "MONITOR_RECALLING_TICKET_ALARM",
    },
    BACKOFFICE: {
        CALL_TICKET: "CALL_TICKET",
        TICKET_GENERATED: "BACKOFFICE_TICKET_GENERATED",
        PENDING_TICKETS: "PENDING_TICKETS",
        NEW_PENDING_TICKETS: "NEW_PENDING_TICKETS",
        FINISH_TICKET: "BACKOFFICE_FINISH_TICKET",
        TICKET_SERVED: "TICKET_SERVED",
        RECALLING_TICKET_ALARM: "BACKOFFICE_RECALLING_TICKET_ALARM",
    },
}