export const EVENTS = {
    GENERAL: {
        CONNECT: "connect",
        DISCONNECT: "disconnect",
        TERMINAL_STATUS: "TERMINAL_STATUS",
        MAX_PENDING_QUEUE_ALERT_ON: "MAX_PENDING_QUEUE_ALERT_ON",
    },
    TOTEM: {
        CREATE_TICKET: "CREATE_TICKET",
        TICKET_CREATED: "TICKET_CREATED",
    },
    MONITOR: {
        TICKET_TAKEN: "TICKET_TAKEN",
        RECALL_TICKET: "RECALL_TICKET",
    },
    BACKOFFICE: {
        TAKE_TICKET: "TAKE_TICKET",
        RECALL_TICKET: "RECALL_TICKET",
        FINISH_TICKET: "FINISH_TICKET",
        TICKET_FINISHED: "TICKET_FINISHED",
        TICKET_TAKEN: "TICKET_TAKEN",
    },
}